version: 2 # schema version

generates:
  - migration-tool: "flyway" # migration tool so we can generate versioned migration scripts
    directory: "/" # directory to generate migration scripts in
    suffix: "YYYY_MM_DD" # suffix to append to the table name
    resolution: "daily" # daily, weekly, monthly, yearly, hourly, table might currently have daily partitions but you could decide to switch to say monthly
    past: 2 # how many partitions to create in the past, if we find such partitions already and they are still part of the
    # partition tree after the retention then we don't create migration scripts for them
    future: 1 # how many partitions to create in the future, current plus number of future
    retention: 24 # how many partitions to keep altogether, if a partition is older then we generate drop statement for it
    create-default: true # if you want to create a default partition or not (if not exists by default)
    tables:
      users:
        schema: "public"
        partitions:
          schema: "partitions" # useful if partition schema is different from the parent schema
          tablespace: "tablespace"
          storage_parameters:
            fillfactor: 90
            autovacuum_enabled: false
        suffix: "YYYY_MM_DD"
        resolution: "daily"
        template_table: "users_template"
        past: 2
        future: 1
        retention: 24
        create-default: true
        fall-back-to-latest-partition-for-template: true # fall back to latest partition if template table doesn't exist
      transactions:
        schema: "partitions"
        suffix: "YYYY_MM_DD"
        resolution: "daily"
        template_table: "transactions_template"
        fall-back-to-default-for-template: true # fall back to default if template table doesn't exist
        past: 2
        future: 1
        retention: 24
        create-default: true
    schedule:
      interval: "weekly"
    groups: # by default we create one file per partitioned table, this controls if you want everything in one file (*) or you want specific partitioned table partitions in one file
      audit-tables:
        patterns:
          - "audit" # audit tables and user partition in one file
          - "users"
