---
generates:
  directory: "tests"
  migration-tool:
    name: "flyway"  # The migration tool to use.
    version: "11.8.0"  # The version of the migration tool.
  name_template: "{table_schema}__{table_name}__YYYY_MM"
  interval: "1 mon"
  tables:
    - table_schema: "public"
      table_name: "transactions"
      file_name_template: "{description}.result"
      description:
        make: "defaults"
