services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    user: root
    command: sh -c "pg-start -v 17 && pg-generate-partitions -c /migrations/config.yml && pg-expire-partitions -c /migrations/config.yml"
    volumes:
      - .:/migrations
