---
# yamllint disable rule:line-length
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: test
    user: root
    tty: true
    command: >
      sh -c "
        pg-start -v ${PGVERSION} &&
        pgp-migrate -m ${MIGRATION_DIRECTORY} -t ${MIGRATION_TOOL} -v ${MIGRATION_TOOL_VERSION} && \
        tests/setup.sh -v ${PGVERSION} && \
        pg_prove --username=postgres --dbname=postgres --verbose --failures tests/t/*.sql && \
        bash shellspec tests/spec
      "
