---
# yamllint disable rule:line-length
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: test
    user: root
    tty: true
    command: >
      sh -c "
        pg-start -v ${PGVERSION:-17} &&
        tests/resources/setup.sh -v ${PGVERSION:-17} && \
        PGOPTIONS='--client_min_messages=warning' pg_prove --username=postgres --dbname=postgres --verbose --failures tests/t/*.sql && \
        PGOPTIONS='--client_min_messages=warning' bash shellspec tests/spec
        #&&
        #pgp-make-partitions -c /migrations/config.sample.yaml
        # pg-expire-partitions -c /migrations/config.yml
      "
    volumes:
      - .:/migrations
