-- CREATE TABLE IF NOT EXISTS public.enrichment
-- (
--     ledger_id uuid NOT NULL,
--     ledger_type text COLLATE pg_catalog."default",
--     transaction_id uuid NOT NULL,
--     account_id uuid NOT NULL,
--     created_at timestamp with time zone NOT NULL,
--     expires_at timestamp with time zone NOT NULL,
--     data jsonb NOT NULL,
--     created timestamp with time zone NOT NULL,
--     updated timestamp with time zone NOT NULL,
--     CONSTRAINT enrichment_pkey PRIMARY KEY (ledger_id, expires_at)
-- ) PARTITION BY RANGE (expires_at);

-- CREATE TABLE IF NOT EXISTS public.tbl_con
-- (
--     ledger_id uuid NOT NULL,
--     expires_at timestamp with time zone NOT NULL,
--     created timestamp with time zone,
--     data jsonb,
--     CONSTRAINT tbl_con_pkey PRIMARY KEY (ledger_id, expires_at),
--     CONSTRAINT chk CHECK (1 = 1)
-- );

-- CREATE INDEX IF NOT EXISTS tbl_con_created_expires_at_idx
--     ON public.tbl_con USING btree
--     (created ASC NULLS LAST, expires_at ASC NULLS LAST)
--     TABLESPACE pg_default;
