name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        postgresql:
          - 16
          # - 17

    name: 🐘 PostgreSQL ${{ matrix.postgresql }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bolajiwahab/pgpartium:0.0.7
      options: --user root
    steps:
      - name: Start PostgreSQL ${{ matrix.postgresql }}
        run: pg-start -v ${{ matrix.postgresql }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate partitions using ${{ matrix.postgresql }}
        run: pg-generate-partitions -c config.yml

      - name: list files
        run: cat enrichment.sql

      # - name: Install Git
      #   run: apt-get update && apt-get install -y git

      - name: Check for uncommitted changes
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: generate-partitions
