name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        postgresql:
          - 16
          - 17

    name: 🐘 PostgreSQL ${{ matrix.postgresql }}
    runs-on: ubuntu-latest
    container: ghcr.io/bolajiwahab/pgpartium:0.0.3@sha256:2d8a490b0d0adf34f3a9fc47ad96d2a6c610663e1a8e265d6077eefe69e3982e
    steps:
      - name: Start PostgreSQL ${{ matrix.postgresql }}
        run: pg-start -v ${{ matrix.postgresql }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test extension on PostgreSQL ${{ matrix.postgresql }}
        run: generate-partitions -c config.yml
