name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        postgresql:
          - 16
          - 17

    name: 🐘 PostgreSQL ${{ matrix.postgresql }}
    runs-on: ubuntu-latest
    container: ghcr.io/bolajiwahab/pgpartium:0.0.1@sha256:eb9f509bddbbec88573811491c23a47cab7bf83388020910b3f7a0933172b86e
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start PostgreSQL ${{ matrix.postgresql }}
        run: generate-partitions -v ${{ matrix.postgresql }} -c config.yml
