---
# yamllint disable rule:line-length
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install and run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgresql:
          - 13
          - 14
          - 15
          - 16
          - 17
        include:
          - tool: flyway
            version: 11.8.0
            migration_path: tests/migrations/flyway
          - tool: go-migrate
            version: 4.18.3
            migration_path: tests/migrations/go-migrate
    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          PGVERSION=${{ matrix.postgresql }} \
          MIGRATION_TOOL=${{ matrix.tool }} \
          MIGRATION_TOOL_VERSION=${{ matrix.version }} \
          MIGRATION_DIRECTORY=${{ matrix.migration_path }} ./run_tests.sh
