---
# yamllint disable rule:line-length
name: Generate

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  packages: read
  contents: write

jobs:
  test:
    strategy:
      matrix:
        postgresql:
          - 16

    name: 🐘 PostgreSQL ${{ matrix.postgresql }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bolajiwahab/pgpartium:0.0.8
      options: --user root
    services:
      # postgres:
      #   # Docker Hub image
      #   image: postgres
      #   # Provide the password for postgres
      #   env:
      #     POSTGRES_PASSWORD: postgres
      #   # Set health checks to wait until postgres has started
      #   options: >-
      #     --health-cmd pg_isready
      #     --health-interval 10s
      #     --health-timeout 5s
      # --health-retries 5
      db:
        image: postgres:${{ matrix.postgresql }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - name: Start PostgreSQL ${{ matrix.postgresql }}
        run: pg-start -v ${{ matrix.postgresql }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make partitions using ${{ matrix.postgresql }}
        run: pgp-make-partitions -c tests/fixtures/make_partitions/defaults.yaml -s db

      # - name: list files
      #   run: cat enrichment.sql

      - name: Check for uncommitted changes
        run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: generate-partitions
